import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import { Suspense } from "react";
import { connection } from 'next/server'
import { modoCsp } from '@/lib/server/csp'


// Con nonce (CSP_MODO distinto de 'vigente') los scripts de Next llevan uno distinto por visita y las paginas se renderizan en cada pedido
export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  if (modoCsp() !== 'vigente') await connection()
  return (
    <html
      lang="es"
      className="h-full antialiased"
    >
      <body className="min-h-full flex flex-col">
        <Suspense fallback={<div>Cargando plataforma...</div>}>
          {children}
        </Suspense>
      </body>
    </html>
  );
}
