import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import { Suspense } from "react";

// Los scripts de Next llevan un nonce distinto por visita (lo genera proxy.ts): las paginas se renderizan en cada pedido
export const dynamic = 'force-dynamic'

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="es"
      className="h-full antialiased"
    >
      <body className="min-h-full flex flex-col">
        <Suspense fallback={<div>Cargando plataforma...</div>}>
          {children}
        </Suspense>
      </body>
    </html>
  );
}
